[mongodb]
mongodb.daws86s.in


[catalouge]
172.31.26.71
172.31.26.71
172.31.26.71
172.31.26.71
172.31.26.71

[frontend]
172.31.17.124
172.31.17.124

[cart]
172.31.26.71

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

;[local:vars]
;NAME=from inventory
 ;COURSE=Ansible
 ;DURATION=10HRS
 ;TRAINER=Sivakumar
